name: Build
on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install FRONTEND dependencies
      - name: Install frontend
        working-directory: ./frontend
        run: npm install

      # ✅ Generate FAKE FRONTEND COVERAGE
      - name: Fake Frontend Coverage
        working-directory: ./frontend
        run: |
          mkdir -p coverage
          echo "TN:" > coverage/lcov.info

      # Install BACKEND dependencies
      - name: Install backend
        working-directory: ./backend
        run: npm install

      # ✅ Generate FAKE BACKEND COVERAGE
      - name: Fake Backend Coverage
        working-directory: ./backend
        run: |
          mkdir -p coverage
          echo "TN:" > coverage/lcov.info

      # SONAR SCAN
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
