name: Build
on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install FRONTEND dependencies
      - name: Install frontend
        working-directory: ./frontend
        run: npm install

      # Run FRONTEND tests with coverage
      - name: Frontend tests
        working-directory: ./frontend
        run: npm test -- --coverage

      # Install BACKEND dependencies
      - name: Install backend
        working-directory: ./backend
        run: npm install

      # Run BACKEND tests with coverage
      - name: Backend tests
        working-directory: ./backend
        run: npm test -- --coverage

      # SONAR SCAN
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
